name: Deploy Swagger

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install deps
      run: |
        pip install --upgrade pip setuptools
        pip install -r requirements.txt

    - name: Build docs
      run: mkdir -p docs

    - name: Create HTML
      run: |
        cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>Academic API - Swagger</title>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css">
          <style>
            body { margin: 0; padding: 0; }
          </style>
        </head>
        <body>
          <div id="swagger-ui"></div>
          <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
          <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-standalone-preset.js"></script>
          <script>
            window.onload = function() {
              SwaggerUIBundle({
                url: "./schema.json",
                dom_id: '#swagger-ui',
                presets: [
                  SwaggerUIBundle.presets.apis,
                  SwaggerUIStandalonePreset
                ],
                layout: "StandaloneLayout"
              });
            };
          </script>
        </body>
        </html>
        EOF

    - name: Generate Schema
      run: |
        python -c "
        import json, os
        os.environ['DJANGO_SETTINGS_MODULE'] = 'core.settings'
        import django
        django.setup()
        from drf_yasg.generators import SchemaGenerator
        generator = SchemaGenerator(title='Academic API')
        schema = generator.get_schema()
        with open('docs/schema.json', 'w') as f:
          json.dump(schema, f, indent=2)
        "

    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

    - name: Deploy Pages
      uses: actions/deploy-pages@v2
